### PR TITLE
Migrate to null safety.

### PR DESCRIPTION
**Pull request by andyduke**

### CODE REVIEW

**Comment by higorlapacw** [comment]
Did you forget to request a reviewer, @andyduke?

**Comment by andyduke** [comment]
> 
> 
> Did you forget to request a reviewer, @andyduke?

How can I do this now?

**Comment by higorlapacw** [comment]
> > Did you forget to request a reviewer, @andyduke?
> 
> How can I do this now?

In the reviewers section in the right side. Click on the engine and select one.

**Comment by andyduke** [comment]
> 
> 
> > > Did you forget to request a reviewer, @andyduke?
> > 
> > 
> > How can I do this now?
> 
> In the reviewers section in the right side. Click on the engine and select one.

I do not have a gear icon in Reviewers, apparently because I do not have the authority to access someone else's repository.

**Comment by jorishermans** [comment]
Sorry @andyduke, I will check this in the evening!

**Comment by jorishermans** [comment]
@andyduke do you know if it would be best to increase major version number for this, or will a minor version bump enough?

**Comment by andyduke** [comment]
> 
> 
> @andyduke do you know if it would be best to increase major version number for this, or will a minor version bump enough?

According to the [article by Flutter team](https://dart.dev/null-safety/migration-guide#package-version), it is better to increase the major version number.

**Comment by jorishermans** [comment]
Nice thanks!

**Pull request merged**
